export default {
	ADD_CART_ITEM: 'ADD_CART_ITEM',
	REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
	REMOVE_FROM_SHOP: 'REMOVE_FROM_SHOP',
	CHANGE_ACTIVE_CATEGORY: 'CHANGE_ACTIVE_CATEGORY',
	TOGGLE_FAVORITE: 'TOGGLE_FAVORITE',
	CHANGE_FILTER_BY: 'CHANGE_FILTER_BY'
};